### ISSUE TITLE
System.IO.FileNotFoundException on startup/install

### ISSUE THREAD

**Issue by bananamufu** [DynamicsNinja/InAppNotificationBuilder#3]
Since updating to version 1.2021.12.1, the following error occurs on startup of the XrmToolbox or on installation of the tool:

`System.IO.FileNotFoundException: The file or assembly "System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" or one of its dependencies was not found. The system cannot find the specified file.
Dateiname: "System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimePropertyInfo.get_Signature()
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.PopulateProperties(Filter filter, RuntimeType declaringType, Dictionary`2 csPropertyInfos, Boolean[] usedSlots, ListBuilder`1& list)
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.PopulateProperties(Filter filter)
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.GetListByName(Char* pName, Int32 cNameLen, Byte* pUtf8Name, Int32 cUtf8Name, MemberListType listType, CacheType cacheType)
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.Populate(String name, MemberListType listType, CacheType cacheType)
   at System.RuntimeType.GetPropertyCandidates(String name, BindingFlags bindingAttr, Type[] types, Boolean allowPrefixLookup)
   at System.RuntimeType.GetProperties(BindingFlags bindingAttr)
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.<GetExportMembers>d__34.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.HasExports()
   at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsPartDiscoverable()
   at System.ComponentModel.Composition.AttributedModel.AttributedModelDiscovery.CreatePartDefinitionIfDiscoverable(Type type, ICompositionElement origin)
   at System.ComponentModel.Composition.Hosting.TypeCatalog.get_PartsInternal()
   at System.ComponentModel.Composition.Hosting.TypeCatalog.GetEnumerator()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.ComponentModel.Composition.Hosting.DirectoryCatalog.Refresh()
   at XrmToolBox.PluginManagerExtended.RescanIfRequired()
   at XrmToolBox.PluginManagerExtended.Recompose()
   at XrmToolBox.New.PluginsForm.ReloadPluginsList()
   at XrmToolBox.New.NewForm.<tsddbTools_DropDownItemClicked>d__79.MoveNext()`

Removing the .dll from the plugin folder solves the error and lets the toolbox start up again.

**Comment by DynamicsNinja** [comment]
Try updating XTB version

**Comment by bananamufu** [comment]
I'm on the newest version available for me (v1.2021.12.53)

**Comment by DynamicsNinja** [comment]
Did you restart XTB after updating the tool? I'm on the v1.2021.12.53 of XTB and it's working just fine.

**Comment by DynamicsNinja** [comment]
Also if you open the XTB root folder (where you can find the XrmToolBox.exe file), can you see the System.Memory.dll file there? If not, something went wrong with the update, you should definitely download the latest version and unpack it manually.

**Comment by bananamufu** [comment]
Manual re-unpacking did the trick 👍 wonder what went wrong there..
